[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5174
  port = 8888

[[redirects]]
  from = "/api/metar"
  to = "/.netlify/functions/metar"
  status = 200
  force = true

[[redirects]]
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200
  force = true

[[redirects]]
  from = "/api/aircrafts"
  to = "/.netlify/functions/aircrafts"
  status = 200
  force = true

[[redirects]]
  from = "/api/aircraft-detail"
  to = "/.netlify/functions/aircraft-detail"
  status = 200
  force = true

[[redirects]]
  from = "/api/airspace-use-plan"
  to = "/.netlify/functions/airspace-use-plan"
  status = 200
  force = true

[[redirects]]
  from = "/api/weather/llsigwx.pdf"
  to = "/.netlify/functions/llsigwx"
  status = 200
  force = true

[[redirects]]
  from = "/api/weather/stations"
  to = "/.netlify/functions/weather-stations"
  status = 200
  force = true

[[redirects]]
  from = "/api/rainviewer"
  to = "/.netlify/functions/rainviewer"
  status = 200
  force = true


[[redirects]]
  from = "/api/notams"
  to = "/.netlify/functions/notams"
  status = 200
  force = true
